In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas

In [4]:
a = np.zeros((2,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
a.shape

(2, 6)

In [8]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
b[1:2]

array([[0., 1., 0.]])

In [17]:
c = np.zeros((2,3,4))
print(c[1:2,:])
print(c[1:2])
print(c[1])

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
A = np.array(np.random.rand(5,2))
B = np.array(np.random.rand(5,2))
rmse = np.sqrt( np.mean( (A - B)**2))
print(rmse)
rmse = np.sqrt(((A - B)**2).T @ ((A - B)**2) * (1/A.shape[0]))
print(rmse)

0.35499063869444714
[[0.09034381 0.13808898]
 [0.13808898 0.23646211]]
